### ISSUE TITLE
In the Dispatch New Incident script, modify the wording of two 'questions' and add a Notification Source pop-up menu

### ISSUE THREAD

**Issue by jim-mcgowan** [redcross/dcsops#263]
In the Dispatch New Incident script, modify the wording of two 'questions' and add a Notification Source pop-up menu:

<img width="470" alt="Dispatch New Incident" src="https://user-images.githubusercontent.com/4147733/88398541-2732a480-cd8b-11ea-8bdc-4641a0d6c1e8.png">

**Comment by kfogel** [comment]
Estimate: maybe Tiny, but likely Small.  Not ideal for a volunteer, but possible.

**Comment by kfogel** [comment]
Estimate: Tiny to Small.

When people type in the wrong report date, there's currently no way to fix it.  There should be a way for properly authorized admins to fix it, though.  

Not great for a volunteer, because it involves the permissions system.

**Comment by frankduncan** [comment]
For this, where does "Notification Source" come from?  Is that already on existing incidents somewhere?

**Comment by OhMcGoo** [comment]
It's the same **Source*** pop-up found when you select the **Notification of Incident** in the **Timeline** of an incident report. This example can be found at https://www.dcsops.org/incidents/illinois/incidents/21-2789#inc-timeline:

![Source*](https://user-images.githubusercontent.com/4147733/108720868-f7957780-74e6-11eb-812c-1253fff7db4b.png)

**Comment by frankduncan** [comment]
Ah, interesting.  The problem is, there's nowhere to put this information.  Right now, that's getting put in the Event Log, as a field on that timeline entry.  If we take this input during the incident creation as part of the Dispatch Console, we'll either need to create a "Notification of Incident" Timeline entry, and put it there, or we have to put this on the base incident and display it on the main page.  At that point, we need to decide whether it still belongs in that Timeline entry.

**Comment by jim-mcgowan** [comment]
Sorry . . . I forgot to touch on this. It SHOULD simply create the **Notification of Incident** timeline entry (as part of the incident report creation process).
