### ISSUE TITLE
When attempting to add a New Price List Item, the application crashes

### ISSUE THREAD

**Issue by jim-mcgowan** [redcross/dcsops#264]
When attempting to add a new Price List Item, the application crashes.

![New Price List Item](https://user-images.githubusercontent.com/4147733/88398943-b8098000-cd8b-11ea-8f5f-229b260188ec.png)

https://www.dcsops.org/scheduler_admin/price_list_items

![We hit a snag     ](https://user-images.githubusercontent.com/4147733/88398956-bf308e00-cd8b-11ea-8857-bc1026f894d4.png)

**Comment by kfogel** [comment]
Estimate: probably Tiny to Small.

The usual reason something like this happens is that the price list has validators about what you're allowed to do, but ActiveAdmin isn't configured properly to supply information for those validators to use.  The validator is looking for an attribute `location` but that attribute isn't present.  The fix is simple: make it be present via ActiveAdmin.

However, this does require acquiring some knowledge of the application to resolve.  E.g., this is an issue we'd give to someone who's joining the team on a long-term basis.  It might not be great for a volunteer looking for a one-off issue that's quick to solve and doesn't require a lot of up-front investment.

**Comment by frankduncan** [comment]
This was actually caused by the sequence for this table getting a weird value.  I've updated production to set it so that the next value will be an id that does not fail.  (Incidentally, if you kept trying over and over again, it would have eventually succeeded since each failure incremented the sequence value by 1)
